export const actionTypes = {
    ADD_POST: "ADD_POST",
    TOGGLE_EDIT_MODE: "TOGGLE_EDIT_MODE",
    SAVE_POST: "SAVE_POST",
    ADD_FIELD: "ADD_FIELD",
    DELETE_FIELD: "DELETE_FIELD",
    CHANGE_FIELD: "CHANGE_FIELD",
    DELETE_POST: "DELETE_POST",
    INIT_POSTS: "INIT_POSTS",
    SUCCESSFUL_SINGUP: "SUCCESFUL_SINGUP",
    AUTH_ERROR: "AUTH_ERROR",
    AUTH_LOGOUT: "AUTH_LOGOUT",
    TOGGLE_POST_PRIVACY: "TOGGLE_POST_PRIVACY"
}